# -*- coding: utf-8 -*-
"""exe2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEWWi0yn9Fp4XSTnyvNi5vMk2rSrkNxZ
"""

def fibonacci(n):
    """
    Função que retorna o n-ésimo número da sequência de Fibonacci.
    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

# Lê o número informado pelo usuário
num = int(input("Informe um número: "))

# Verifica se o número pertence à sequência de Fibonacci
pertence = False
i = 0
while fibonacci(i) <= num:
    if fibonacci(i) == num:
        pertence = True
        break
    i += 1

# Imprime a sequência de Fibonacci e se o número pertence ou não
if pertence:
    print("O número", num, "pertence à sequência de Fibonacci.")
else:
    print("O número", num, "não pertence à sequência de Fibonacci.")
print("Sequência de Fibonacci até o número", num, ":")
i = 0
while fibonacci(i) <= num:
    print(fibonacci(i))
    i += 1